### PR TITLE
1st keyboard page build but all keys are not working

### PR DESCRIPTION
**Pull request by mhamidjamil**

### CODE REVIEW

**Review by wasey-rao — APPROVED** [review]
fix the function keys and other special key then I'll merge it.

**Review by wasey-rao — APPROVED** [review]
I don't think its complete keyboard, like I can't use shift to enter capital or special symbols, right ? @mhamidjamil

**Comment by mhamidjamil** [comment]
Yes @wasey-rao, you are right, but my main task till now is to make a keyboard which can used to trigger function and special keys, regarding other stuff, you can also use serial terminal (not now in coming version) and BLE (working) to send strings so they both complete the keyboard functionality.

**Comment by wasey-rao** [comment]
@mhamidjamil what is use don't have BLE device?
how ever implement Serial to HID as soon as possible, I'm merging it now as it full fill the requirements of #3

**Pull request merged**
